[package]
name = "wabbit_compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"
wabbit_proc_macros = { path = "wabbit_proc_macros" }

[dev-dependencies]
insta = "1.39.0"
rstest = "0.21.0"
